; cave parameters and map for one cave
cave_parameter_data                   ; Starts at address 4e40
param_diamond_value
;TODO: Testing
;    !byte $0a                          ; Diamond value
  !byte $ff
param_diamond_extra_value
;TODO: Testing
;    !byte $0f                          ; Diamond extra value
  !byte $ff
param_diamonds_required
;TODO: Testing
  !byte 2,3,4,5,6
;    !byte $0c, $0c, $0c, $0c, $0c      ; Diamonds required for each difficulty level x5
param_cave_time
  !byte 60,70,80,90,95
;    !byte $96, $6e, $46, $28, $1e      ; Cave time for each difficulty level x5
param_amoeba_magic_wall_time
;TODO: Testing
  !byte 60
;    !byte $00                          ; Amoeba or Magic Wall time
param_initial_fill_tile
    !byte $01                          ; Initial fill tile - usually dirt, sometimes space
param_random_seeds
    !byte $0a, $0b, $0c, $0d, $0e      ; Random seed for pseudo-random routine for each difficulty level x5
param_tile_probability
    !byte $3c, $32, $09, $00           ; Tile probability for up to four tiles / objects x4
param_tile_for_probability
    !byte $00, $05, $04, $00           ; Tile / object related to the probability x4
param_intermission
    !byte $00                          ; Intermission indicator (0 for normal cave, 1 for intermission / bonus cave)
param_colours
    !byte $05, $01, $07                ; Cave colour scheme x3 colours
param_rockford_start
  !byte $02, $03                     ; Rockford start row and column
param_rockford_end
;TODO: Testing
  !byte $02, $04
;    !byte $10, $26                     ; Rockford exit row and column
param_slime_permeability
;TODO: Testing
  !byte $0a
;    !byte $00                          ; Slime permeability
param_tile_for_prob_below
    !byte $00, $00, $00, $00           ; Additional tile below the one generated by pseudo-random routine
param_bombs                           ; For homebrew bombs element
;TODO: Testing
  !byte 2
;    !byte $00                          ; 0 = no bombs, otherwise number of bombs available
param_zero_gravity_time               ; New feature used to control use of gravity (whether rocks/diamonds fall)
;TODO: Testing
; !byte $20
    !byte 0                            ; 0 = no zero-gravity time (always gravity/normal), 1-$fe = time until gravity back on, $ff = always zero gravity
param_border_tile                     ; Border tile, for the standard steelwall, set to 3
    !byte $03                          ; Is just applied to the top and bottom rows as the side borders are specified in the cave file
param_future_use
    !byte $00, $00, $00, $00, $00      ; For potential future use (cannot be removed)

cave_map_data  ; 20 x 40 empty cave, each byte represents 2 tiles (each nibble)
  !byte $3f, $ff, $ff, $ff, $f5, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $f0, $f4, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $ff, $fd, $9f, $ff, $e0, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $fb, $ff, $fe, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $fc, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $f4, $ff, $ff, $ff, $60, $00, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $32, $22, $22, $22, $22, $22, $22, $22, $22, $22, $22, $22, $22, $22, $22, $2f, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $1f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $1f, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $ff, $f2, $22, $22, $22, $22, $22, $22, $22, $22, $22, $22, $22, $22, $22, $22, $23
  !byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $03
  !byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
  !byte $3f, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $f3
